version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: lintas-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: lintas_wahana
      MYSQL_USER: lw_user
      MYSQL_PASSWORD: lw_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-databases.sql:/docker-entrypoint-initdb.d/01-init-databases.sql

volumes:
  mysql_data:
